name = "ctv-api"
main = "worker/worker.js"
compatibility_date = "2024-01-01"

# Cloudflare D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "vdt"
database_id = "19917e57-ced3-4fc3-adad-368a2e989ea7"

# Environment Variables
[vars]
# URL của Google Apps Script để đồng bộ dữ liệu
GOOGLE_APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbwh4Az3BjmNMan7Ik_FxcsmDSSuUE4lWMBgcPBlsITYN39bWfHztZK9VOS930rrin3dEA/exec"
# Secret key để bảo mật thông báo Telegram
SECRET_KEY = "VDT_SECRET_2025_ANHIEN"
